apiVersion: v1
kind: Service
metadata:
  name: tino-main-service
  namespace: tino-sh
spec:
  selector:
    app: tino-main
  ports:
    - port: 7777
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tino-projects-service
  namespace: tino-sh
spec:
  selector:
    app: tino-projects
  ports:
    - port: 7777
      targetPort: 80
