---
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.tino.sh/tino-main
    context: ../../
    docker:
      target: main
  - image: registry.tino.sh/tino-projects
    context: ../../
    docker:
      target: projects
  - image: registry.tino.sh/tino-roeter
    context: ../../
    docker:
      target: roeter
deploy:
  kustomize: {}
